function result = sl_best_practices()
% SL_BEST_PRACTICES 返回 Simulink 建模最佳实践与反模式规则
%   result = sl_best_practices()
%
%   基于 simulink/skills 项目的 8 大禁止做法 + 现代 API 推荐
%   这些规则已嵌入到 sl_add_block_safe、sl_add_line_safe 等函数中
%
%   输出: struct
%     .antiPatterns     - 8 大反模式规则列表
%     .modernAPIs       - 推荐的现代 API
%     .versionPractices - 版本相关实践建议

    % ===== 8 大反模式规则 =====
    antiPatterns = cell(1, 8);
    
    % #1: Sum 块
    antiPatterns{1} = struct( ...
        'rule', '#1', ...
        'name', 'Discourage Sum Block', ...
        'level', 'warning', ...
        'description', 'Sum block is discouraged in modern Simulink modeling', ...
        'reason', 'Sum block has ambiguous behavior with multiple inputs and can cause confusion', ...
        'suggestion', 'Use Add block for addition, Subtract block for subtraction', ...
        'alternatives', {'Add', 'Subtract'}, ...
        'enforcedIn', {'sl_add_block_safe'});
    
    % #2: To Workspace 块
    antiPatterns{2} = struct( ...
        'rule', '#2', ...
        'name', 'Discourage To Workspace Block', ...
        'level', 'warning', ...
        'description', 'To Workspace block is discouraged for signal recording', ...
        'reason', 'To Workspace blocks clutter the model and are harder to manage programmatically', ...
        'suggestion', 'Use Signal Logging via sl_signal_logging or SimulationInput', ...
        'alternativeCommand', 'sl_signal_logging', ...
        'enforcedIn', {'sl_add_block_safe'});
    
    % #3: 裸 add_line
    antiPatterns{3} = struct( ...
        'rule', '#3', ...
        'name', 'Prefer connectBlocks over add_line', ...
        'level', 'info', ...
        'description', 'add_line is legacy; connectBlocks is the modern API (R2024b+)', ...
        'reason', 'connectBlocks handles port resolution automatically and is more robust', ...
        'suggestion', 'Use Simulink.BlockDiagram.connectBlocks when available, fallback to add_line', ...
        'enforcedIn', {'sl_add_line_safe'});
    
    % #4: 裸 Position
    antiPatterns{4} = struct( ...
        'rule', '#4', ...
        'name', 'Discourage Manual Position Setting', ...
        'level', 'warning', ...
        'description', 'Manually setting Position is fragile and breaks across MATLAB versions', ...
        'reason', 'Position coordinates are version-dependent and break when blocks are added/removed', ...
        'suggestion', 'Use sl_arrange_model for automatic layout after model construction', ...
        'alternativeCommand', 'sl_arrange_model', ...
        'enforcedIn', {'sl_arrange_model'});
    
    % #5: 裸 set_param + sim
    antiPatterns{5} = struct( ...
        'rule', '#5', ...
        'name', 'Discourage set_param + sim Pattern', ...
        'level', 'error', ...
        'description', 'Using set_param to modify model before sim() is unsafe and non-reproducible', ...
        'reason', 'set_param mutates global model state; sim() with modified state is not reproducible', ...
        'suggestion', 'Use Simulink.SimulationInput to configure simulation parameters programmatically', ...
        'alternativeCommand', 'Simulink.SimulationInput', ...
        'enforcedIn', {'sl_validate_model'});
    
    % #6: 手动 Subsystem
    antiPatterns{6} = struct( ...
        'rule', '#6', ...
        'name', 'Discourage Manual Subsystem Creation', ...
        'level', 'warning', ...
        'description', 'Manually creating Subsystem and moving blocks into it is error-prone', ...
        'reason', 'Manual subsystem creation can break signal lines and block connections', ...
        'suggestion', 'Use createSubsystem API to automatically group blocks into subsystems', ...
        'alternativeCommand', 'Simulink.SubSystem.createSubsystem', ...
        'enforcedIn', {});
    
    % #7: 忽略未连接端口
    antiPatterns{7} = struct( ...
        'rule', '#7', ...
        'name', 'Check Unconnected Ports', ...
        'level', 'warning', ...
        'description', 'Unconnected ports indicate incomplete model construction', ...
        'reason', 'Unconnected ports cause simulation errors or unexpected behavior', ...
        'suggestion', 'Use sl_inspect_model to check for unconnected ports after model construction', ...
        'alternativeCommand', 'sl_inspect_model', ...
        'enforcedIn', {'sl_inspect_model', 'sl_validate_model'});
    
    % #8: 维度 mismatch
    antiPatterns{8} = struct( ...
        'rule', '#8', ...
        'name', 'Check Port Dimensions Before Connecting', ...
        'level', 'error', ...
        'description', 'Connecting ports with mismatched dimensions causes simulation errors', ...
        'reason', 'Dimension mismatch is a common source of simulation failures', ...
        'suggestion', 'Check port dimensions before connecting; add reshape or conversion block if needed', ...
        'enforcedIn', {'sl_add_line_safe'});
    
    % ===== 推荐的现代 API =====
    modernAPIs = cell(1, 5);
    modernAPIs{1} = struct( ...
        'name', 'Simulink.BlockDiagram.connectBlocks', ...
        'introduced', 'R2024b', ...
        'replaces', 'add_line', ...
        'usage', 'Simulink.BlockDiagram.connectBlocks(model, srcBlock, dstBlock)', ...
        'benefit', 'Automatic port resolution, more robust than add_line');
    modernAPIs{2} = struct( ...
        'name', 'Simulink.SimulationInput', ...
        'introduced', 'R2016b', ...
        'replaces', 'set_param + sim', ...
        'usage', 'in = Simulink.SimulationInput(model); in = in.setModelParameter(...); out = sim(in);', ...
        'benefit', 'Reproducible, isolated simulation configuration');
    modernAPIs{3} = struct( ...
        'name', 'Simulink.SubSystem.createSubsystem', ...
        'introduced', 'R2018a', ...
        'replaces', 'Manual Subsystem creation', ...
        'usage', 'Simulink.SubSystem.createSubsystem(blocks)', ...
        'benefit', 'Automatic port handling, preserves connections');
    modernAPIs{4} = struct( ...
        'name', 'Simulink.BlockDiagram.arrangeSystem', ...
        'introduced', 'R2018b', ...
        'replaces', 'Manual Position setting', ...
        'usage', 'Simulink.BlockDiagram.arrangeSystem(model)', ...
        'benefit', 'Automatic layout, version-independent');
    modernAPIs{5} = struct( ...
        'name', 'Simulink.BlockDiagram.routeLine', ...
        'introduced', 'R2018b', ...
        'replaces', 'Manual autorouting', ...
        'usage', 'Simulink.BlockDiagram.routeLine(lineHandles)', ...
        'benefit', 'Better routing quality than add_line autorouting');
    
    % ===== 版本相关实践 =====
    versionPractices = cell(1, 4);
    versionPractices{1} = struct( ...
        'topic', 'JSON Encoding', ...
        'practice', 'Use jsonencode (R2018b+) with fallback for R2016a', ...
        'implementation', 'sl_jsonencode.m handles both versions automatically');
    versionPractices{2} = struct( ...
        'topic', 'Model Layout', ...
        'practice', 'Use arrangeSystem (R2018b+) with fallback for R2016a~R2018a', ...
        'implementation', 'sl_arrange_model.m uses topological sort fallback');
    versionPractices{3} = struct( ...
        'topic', 'Block Lookup', ...
        'practice', 'Use sl_block_registry for case-insensitive, fuzzy matching', ...
        'implementation', 'sl_block_registry.m supports aliases and library search fallback');
    versionPractices{4} = struct( ...
        'topic', 'Simulation Compilation', ...
        'practice', 'Use model(''compile'') instead of set_param(''SimulationCommand'',''compile'')', ...
        'reason', 'set_param SimulationCommand not supported in MATLAB Engine mode', ...
        'implementation', 'sl_validate_model.m uses model(''compile'') approach');
    
    % ===== 组装返回 =====
    result = struct();
    result.antiPatterns = antiPatterns;
    result.modernAPIs = modernAPIs;
    result.versionPractices = versionPractices;
    result.version = 'v5.0';
    result.source = 'simulink/skills + matlab-agentic-toolkit';
end
