function result = sl_framework_prompts(action, varargin)
% SL_FRAMEWORK_PROMPTS v11.2 Prompt Template Library for Macro Framework Design
%   result = sl_framework_prompts('system_prompt', taskDescription)
%   result = sl_framework_prompts('output_schema')
%   result = sl_framework_prompts('review_checklist')
%   result = sl_framework_prompts('task_analysis_guide')
%   result = sl_framework_prompts('signal_flow_patterns')
%
% v11.2: Enhanced anti-template constraints
%   - System prompt explicitly declares NO universal framework exists
%   - AI has COMPLETE FREEDOM to design subsystem architecture
%   - Emphasis on first-principles reasoning and domain expertise
%   - Added 'role' field to output schema for subsystem purpose
%   - Added 'reasoning' field for AI to explain design decisions
%
% v11.1: Initial Prompt-Driven AI template library

    switch lower(action)
        case 'system_prompt'
            result = get_system_prompt(varargin{:});
        case 'output_schema'
            result = get_output_schema();
        case 'review_checklist'
            result = get_review_checklist();
        case 'task_analysis_guide'
            result = get_task_analysis_guide();
        case 'signal_flow_patterns'
            result = get_signal_flow_patterns();
        case 'hierarchy_guidance'
            result = get_hierarchy_guidance();
        otherwise
            result = struct('status', 'error', ...
                'message', sprintf('Unknown action: %s. Use: system_prompt, output_schema, review_checklist, task_analysis_guide, signal_flow_patterns, hierarchy_guidance', action));
    end
end

% ===== System Prompt: Guides AI to design macro framework =====
function prompt = get_system_prompt(taskDescription)
    if nargin < 1 || isempty(taskDescription)
        taskDescription = '%TASK_DESCRIPTION%';
    end
    prompt = {[...
        'You are an expert Simulink model designer with deep domain knowledge.', ...
        'Given a task description, you must design a macro framework for the Simulink model.', ...
        '', ...
        'Task: ', taskDescription, ...
        '', ...
        'CRITICAL INSTRUCTION:', ...
        'You have COMPLETE FREEDOM to design the subsystem architecture. ', ...
        'There is NO predefined template or universal framework. ', ...
        'The subsystem division must be SPECIFIC to the task, based on ', ...
        'YOUR domain expertise in physics, control theory, and Simulink modeling.', ...
        '', ...
        'DESIGN PRINCIPLES (apply your expertise, these are GUIDELINES only):', ...
        '1. Analyze the physical system from first principles', ...
        '2. Identify natural subsystem boundaries based on physical domains', ...
        '   Example: For a quadrotor, subsystems might include:', ...
        '     - Attitude_Dynamics (rigid body rotation)', ...
        '     - Motor_Mixer (thrust allocation)', ...
        '     - Position_Controller (trajectory tracking)', ...
        '     - etc. -- but these are just examples, NOT a template!', ...
        '3. Derive governing equations using appropriate physical laws', ...
        '4. Define clear signal interfaces between subsystems using Inport/Outport', ...
        '   SUBSYSTEM INTERFACE RULE (mandatory):', ...
        '   - Subsystem-to-subsystem signals MUST use Inport/Outport standard interfaces', ...
        '   - Goto/From is ONLY for WITHIN-subsystem local signal routing', ...
        '   - NEVER use Goto/From across subsystem boundaries (it creates untraceable global signals)', ...
        '5. Consider: Is there feedback? Multiple control loops? ', ...
        '   Sensor dynamics? Actuator constraints? External disturbances?', ...
        '', ...
        'YOU ARE THE EXPERT. Design the system as a domain specialist would.', ...
        'DO NOT fall back to generic Controller/Plant/Sensor templates ', ...
        'unless they genuinely match the system architecture.', ...
        '', ...
        'OUTPUT FORMAT (JSON):', ...
        '  domain: <detailed domain classification string>', ...
        '  subsystems: [{name, type, role, inputs[], outputs[]}, ...]', ...
        '  signalFlow: [{srcSubsystem, dstSubsystem, signalName, description}, ...]', ...
        '  interfaceSpec: [{subsystem, inports[], outports[]}, ...] (MANDATORY: define Inport/Outport interfaces)', ...
        '  physicsEquations: [{equation, description, variables[], assumptions[]}, ...]', ...
        '  confidence: 0.0-1.0 (your assessment of design quality)', ...
        '  reasoning: <explain your design decisions and why you chose this architecture>', ...
        '  warnings: [string, ...] (potential issues or caveats)', ...
        '', ...
        'HIERARCHICAL DESIGN (CRITICAL -- plan ALL nesting levels):', ...
        'You must now design the COMPLETE subsystem hierarchy, not just the top level.', ...
        'Think recursively: what subsystems naturally contain sub-subsystems?', ...
        '', ...
        'RECURSIVE DESIGN PROCESS:', ...
        '1. Start from the top level: identify major functional blocks', ...
        '2. For EACH top-level subsystem, ask: ', ...
        '   "Does this subsystem contain sub-components with distinct functions?"', ...
        '3. If YES, define child subsystems and repeat step 2 for each child', ...
        '4. Stop when each leaf subsystem performs a SINGLE, well-defined function', ...
        '5. A leaf subsystem should be buildable with basic Simulink blocks', ...
        '   (Integrator, Gain, Sum, Product, etc.) without needing more subsystems', ...
        '', ...
        'NESTING DEPTH LIMITS (HARD CONSTRAINTS -- enforced by Bridge):', ...
        '- [RED] ABSOLUTE MAXIMUM: 5 levels (including top-level subsystems).', ...
        '- Depth = 6: gate_blocked at framework_approve -- design will be REJECTED.', ...
        '- Recommended: 2-3 levels for typical systems.', ...
        '- Depth 4-5: acceptable for genuinely complex hierarchical systems ', ...
        '  (e.g. cascaded controllers, multi-domain plants with sub-models).', ...
        '- Each level must represent a meaningful functional decomposition.', ...
        '- MAAB db_0036: limit hierarchical levels.', ...
        '', ...
        'WARNING: Designs exceeding 5 levels will be BLOCKED.', ...
        'Plan your hierarchy carefully. If you need deeper nesting, ', ...
        'consider flattening or using Model Reference instead.', ...
        '- MAAB db_0038: each subsystem should have a single, clear function', ...
        '', ...
        'ANTI-PATTERNS TO AVOID:', ...
        '- Single-block subsystems (MAAB db_0037)', ...
        '- Empty subsystems with no defined internals', ...
        '- Deep nesting without clear functional boundaries', ...
        '- Mixed abstraction levels', ...
        '', ...
        'UPDATED OUTPUT FORMAT (JSON):', ...
        '  domain: <detailed domain classification> ', ...
        '  subsystems: [{name, type, role, inputs[], outputs[], ', ...
        '    childSubsystems: [{...recursive...}], ', ...
        '    signalFlow: [{srcSubsystem, dstSubsystem, signalName, description}], ', ...
        '    physicsEquations: [{equation, description, variables[], assumptions[]}] ', ...
        '  }]', ...
        '  maxDepth: <maximum nesting depth in this design> ', ...
        '  totalSubsystemCount: <total number of subsystems across all levels> ', ...
        '  confidence: 0.0-1.0 ', ...
        '  reasoning: <explain your design decisions including nesting choices> ', ...
        '  warnings: [string, ...] ', ...
        '', ...
        'YOU ARE THE EXPERT. Design the complete hierarchy as a domain specialist would.', ...
        'A quadrotor flight controller naturally has nested structure (ADRC -> TD/ESO/NLSEF).', ...
        'A simple low-pass filter does not. Let the PHYSICS guide your nesting decisions.', ...
    ]};
end

% ===== Output Schema: Defines expected output structure =====
function schema = get_output_schema()
    schema = struct();
    schema.domain = 'string: detailed domain classification (e.g. aerospace+control, mechanical, multi-domain)';
    schema.subsystems = struct('name', 'string', 'type', 'string', 'role', 'string', ...
        'inputs', 'cell of strings', 'outputs', 'cell of strings');
    schema.signalFlow = struct('srcSubsystem', 'string', 'dstSubsystem', 'string', ...
        'signalName', 'string', 'description', 'string');
    % [P0-3 FIX v11.7] Removed gotoFromPlan from framework-level output schema.
    % Goto/From routing is a micro-design (subsystem-internal) concern.
    % Framework level only defines Inport/Outport interfaces via interfaceSpec.
    schema.interfaceSpec = struct('subsystem', 'string', 'inports', 'cell of strings', ...
        'outports', 'cell of strings');
    schema.physicsEquations = struct('equation', 'string', 'description', 'string', ...
        'variables', 'cell of strings', 'assumptions', 'cell of strings');
    schema.confidence = '0.0 to 1.0';
    schema.reasoning = 'string: explain your design decisions';
    schema.warnings = 'cell of strings';
    schema.childSubsystems = 'recursive: same structure as subsystems (can be nested arbitrarily deep, max 5 levels)';
    schema.maxDepth = 'double: maximum nesting depth across entire design';
    schema.totalSubsystemCount = 'double: total subsystems at all levels';
end

% ===== Review Checklist: What to verify in the framework =====
function checklist = get_review_checklist()
    checklist = {};
    checklist{1} = 'Are all subsystems identified with clear roles and purposes?';
    checklist{2} = 'Do signal flows form a connected graph (no isolated subsystems)?';
    checklist{3} = 'Are physics equations derived from first principles (not generic templates)?';
    checklist{4} = 'Are all input/output signals accounted for in the signal flow?';
    checklist{5} = 'Is the system type correct (open-loop vs closed-loop vs hybrid)?';
    checklist{6} = 'Do all subsystem interfaces use Inport/Outport? (Goto/From is reserved for micro-design)';
    checklist{7} = 'Are there any algebraic loops in the signal flow?';
    checklist{8} = 'Is the confidence assessment honest and justified?';
    checklist{9} = 'Are there any singularities or numerical issues in the equations?';
    checklist{10} = 'Does the subsystem division reflect physical reality, not convenience?';
    checklist{11} = 'Is the design specific to this task (not a generic template)?';
    checklist{12} = 'Does nesting depth exceed the hard limit of 5? (depth > 5 = REJECTED)';
    checklist{13} = 'Are there any single-block subsystems (MAAB db_0037)?';
    checklist{14} = 'Does each subsystem have a single, well-defined function (MAAB db_0038)?';
    checklist{15} = 'Are cross-level interfaces consistent (child I/O matches parent)?';
    checklist{16} = 'Are there any duplicate subsystem paths in the hierarchy?';
    checklist{17} = 'Do all leaf subsystems have defined internal blocks or equations?';
end

% ===== Task Analysis Guide: How to decompose a task =====
function guide = get_task_analysis_guide()
    guide = {};
    guide{1} = 'STEP 1: Identify the physical system being modeled (plant/process)';
    guide{2} = 'STEP 2: Determine if control is needed (feedback, feedforward, open-loop)';
    guide{3} = 'STEP 3: List all physical variables (states, inputs, outputs, disturbances)';
    guide{4} = 'STEP 4: Derive governing equations from conservation laws or variational principles';
    guide{5} = 'STEP 5: Identify coupling between physical domains (mechanical-electrical, etc.)';
    guide{6} = 'STEP 6: Determine signal dimensions (scalar, vector, matrix)';
    guide{7} = 'STEP 7: Map equations to Simulink block types (Integrator, Gain, Sum, Product, etc.)';
    guide{8} = 'STEP 8: Define subsystem boundaries based on physical domain or functional role';
    guide{9} = 'STEP 9: Define Inport/Outport interfaces for each subsystem, then plan routing. Goto/From is ONLY for within-subsystem local signals.';
    guide{10} = 'STEP 10: Assess model complexity and assign confidence level';
end

% ===== Signal Flow Patterns: Common topologies =====
function patterns = get_signal_flow_patterns()
    patterns = {};
    % Closed-loop feedback
    patterns{1} = struct('name', 'closed_loop_feedback', ...
        'description', 'Plant output -> Controller -> Plant input (standard feedback)', ...
        'signalFlow', '{{srcSubsystem,Plant,dstSubsystem,Controller,signalName,measured}, {srcSubsystem,Controller,dstSubsystem,Plant,signalName,control_action}}');
    % Cascade control
    patterns{2} = struct('name', 'cascade_control', ...
        'description', 'Outer loop -> Inner loop -> Plant', ...
        'signalFlow', '{{srcSubsystem,Plant,dstSubsystem,InnerController,signalName,inner_measured}, {srcSubsystem,InnerController,dstSubsystem,Plant,signalName,inner_action}, {srcSubsystem,Plant,dstSubsystem,OuterController,signalName,outer_measured}, {srcSubsystem,OuterController,dstSubsystem,InnerController,signalName,setpoint}}');
    % Feedforward + feedback
    patterns{3} = struct('name', 'feedforward_feedback', ...
        'description', 'Reference -> Feedforward + Feedback Controller -> Plant', ...
        'signalFlow', '{{srcSubsystem,Reference,dstSubsystem,Feedforward,signalName,ref}, {srcSubsystem,Plant,dstSubsystem,Feedback,signalName,measured}, {srcSubsystem,Feedforward,dstSubsystem,Sum,signalName,ff_action}, {srcSubsystem,Feedback,dstSubsystem,Sum,signalName,fb_action}, {srcSubsystem,Sum,dstSubsystem,Plant,signalName,total_action}}');
end

% ===== Hierarchy Guidance: Depth-aware design rules =====
function guidance = get_hierarchy_guidance()
    guidance = {};
    guidance{1} = struct('depth', 1, ...
        'role', 'TOP-LEVEL subsystem. Design its internal architecture with clear sub-component boundaries.', ...
        'blockGuidance', 'You may define child subsystems if needed for functional decomposition.');
    guidance{2} = struct('depth', 2, ...
        'role', 'MID-LEVEL subsystem. Focus on the specific algorithm or physical process.', ...
        'blockGuidance', 'You may create child subsystems if functionally justified, but prefer basic blocks.');
    guidance{3} = struct('depth', 3, ...
        'role', 'LEAF or near-leaf subsystem. Build it with basic Simulink blocks. No more nesting needed.', ...
        'blockGuidance', 'Use only basic blocks (Integrator, Gain, Sum, Product, etc.). Do NOT create more subsystems.');
    guidance{4} = struct('depth', 4, ...
        'role', 'DEEP leaf subsystem. Near the absolute nesting limit.', ...
        'blockGuidance', 'Use ONLY basic blocks. Creating child subsystems requires strong functional justification.');
    guidance{5} = struct('depth', 5, ...
        'role', '[RED] ABSOLUTE MAXIMUM DEPTH. This is the deepest allowed nesting level.', ...
        'blockGuidance', '[RED] Use ONLY basic blocks. Creating child subsystems here will be BLOCKED by Bridge. NO MORE NESTING IS POSSIBLE.');
end
