function result = sl_framework_prompts(action, varargin)
% SL_FRAMEWORK_PROMPTS v11.2 Prompt Template Library for Macro Framework Design
%   result = sl_framework_prompts('system_prompt', taskDescription)
%   result = sl_framework_prompts('output_schema')
%   result = sl_framework_prompts('review_checklist')
%   result = sl_framework_prompts('task_analysis_guide')
%   result = sl_framework_prompts('signal_flow_patterns')
%
% v11.2: Enhanced anti-template constraints
%   - System prompt explicitly declares NO universal framework exists
%   - AI has COMPLETE FREEDOM to design subsystem architecture
%   - Emphasis on first-principles reasoning and domain expertise
%   - Added 'role' field to output schema for subsystem purpose
%   - Added 'reasoning' field for AI to explain design decisions
%
% v11.1: Initial Prompt-Driven AI template library

    switch lower(action)
        case 'system_prompt'
            result = get_system_prompt(varargin{:});
        case 'output_schema'
            result = get_output_schema();
        case 'review_checklist'
            result = get_review_checklist();
        case 'task_analysis_guide'
            result = get_task_analysis_guide();
        case 'signal_flow_patterns'
            result = get_signal_flow_patterns();
        otherwise
            result = struct('status', 'error', ...
                'message', sprintf('Unknown action: %s. Use: system_prompt, output_schema, review_checklist, task_analysis_guide, signal_flow_patterns', action));
    end
end

% ===== System Prompt: Guides AI to design macro framework =====
function prompt = get_system_prompt(taskDescription)
    if nargin < 1 || isempty(taskDescription)
        taskDescription = '%TASK_DESCRIPTION%';
    end
    prompt = {[...
        'You are an expert Simulink model designer with deep domain knowledge.', ...
        'Given a task description, you must design a macro framework for the Simulink model.', ...
        '', ...
        'Task: ', taskDescription, ...
        '', ...
        'CRITICAL INSTRUCTION:', ...
        'You have COMPLETE FREEDOM to design the subsystem architecture. ', ...
        'There is NO predefined template or universal framework. ', ...
        'The subsystem division must be SPECIFIC to the task, based on ', ...
        'YOUR domain expertise in physics, control theory, and Simulink modeling.', ...
        '', ...
        'DESIGN PRINCIPLES (apply your expertise, these are GUIDELINES only):', ...
        '1. Analyze the physical system from first principles', ...
        '2. Identify natural subsystem boundaries based on physical domains', ...
        '   Example: For a quadrotor, subsystems might include:', ...
        '     - Attitude_Dynamics (rigid body rotation)', ...
        '     - Motor_Mixer (thrust allocation)', ...
        '     - Position_Controller (trajectory tracking)', ...
        '     - etc. -- but these are just examples, NOT a template!', ...
        '3. Derive governing equations using appropriate physical laws', ...
        '4. Define clear signal interfaces between subsystems', ...
        '5. Consider: Is there feedback? Multiple control loops? ', ...
        '   Sensor dynamics? Actuator constraints? External disturbances?', ...
        '', ...
        'YOU ARE THE EXPERT. Design the system as a domain specialist would.', ...
        'DO NOT fall back to generic Controller/Plant/Sensor templates ', ...
        'unless they genuinely match the system architecture.', ...
        '', ...
        'OUTPUT FORMAT (JSON):', ...
        '  domain: <detailed domain classification string>', ...
        '  subsystems: [{name, type, role, inputs[], outputs[]}, ...]', ...
        '  signalFlow: [{srcSubsystem, dstSubsystem, signalName, description}, ...]', ...
        '  gotoFromPlan: [{tag, srcSubsystem, dstSubsystems[], signalName}, ...]', ...
        '  physicsEquations: [{equation, description, variables[], assumptions[]}, ...]', ...
        '  confidence: 0.0-1.0 (your assessment of design quality)', ...
        '  reasoning: <explain your design decisions and why you chose this architecture>', ...
        '  warnings: [string, ...] (potential issues or caveats)', ...
    ]};
end

% ===== Output Schema: Defines expected output structure =====
function schema = get_output_schema()
    schema = struct();
    schema.domain = 'string: detailed domain classification (e.g. aerospace+control, mechanical, multi-domain)';
    schema.subsystems = struct('name', 'string', 'type', 'string', 'role', 'string', ...
        'inputs', 'cell of strings', 'outputs', 'cell of strings');
    schema.signalFlow = struct('srcSubsystem', 'string', 'dstSubsystem', 'string', ...
        'signalName', 'string', 'description', 'string');
    schema.gotoFromPlan = struct('tag', 'string', 'srcSubsystem', 'string', ...
        'dstSubsystems', 'cell of strings', 'signalName', 'string');
    schema.physicsEquations = struct('equation', 'string', 'description', 'string', ...
        'variables', 'cell of strings', 'assumptions', 'cell of strings');
    schema.confidence = '0.0 to 1.0';
    schema.reasoning = 'string: explain your design decisions';
    schema.warnings = 'cell of strings';
end

% ===== Review Checklist: What to verify in the framework =====
function checklist = get_review_checklist()
    checklist = {};
    checklist{1} = 'Are all subsystems identified with clear roles and purposes?';
    checklist{2} = 'Do signal flows form a connected graph (no isolated subsystems)?';
    checklist{3} = 'Are physics equations derived from first principles (not generic templates)?';
    checklist{4} = 'Are all input/output signals accounted for in the signal flow?';
    checklist{5} = 'Is the system type correct (open-loop vs closed-loop vs hybrid)?';
    checklist{6} = 'Are Goto/From tags unique and necessary (not over-used)?';
    checklist{7} = 'Are there any algebraic loops in the signal flow?';
    checklist{8} = 'Is the confidence assessment honest and justified?';
    checklist{9} = 'Are there any singularities or numerical issues in the equations?';
    checklist{10} = 'Does the subsystem division reflect physical reality, not convenience?';
    checklist{11} = 'Is the design specific to this task (not a generic template)?';
end

% ===== Task Analysis Guide: How to decompose a task =====
function guide = get_task_analysis_guide()
    guide = {};
    guide{1} = 'STEP 1: Identify the physical system being modeled (plant/process)';
    guide{2} = 'STEP 2: Determine if control is needed (feedback, feedforward, open-loop)';
    guide{3} = 'STEP 3: List all physical variables (states, inputs, outputs, disturbances)';
    guide{4} = 'STEP 4: Derive governing equations from conservation laws or variational principles';
    guide{5} = 'STEP 5: Identify coupling between physical domains (mechanical-electrical, etc.)';
    guide{6} = 'STEP 6: Determine signal dimensions (scalar, vector, matrix)';
    guide{7} = 'STEP 7: Map equations to Simulink block types (Integrator, Gain, Sum, Product, etc.)';
    guide{8} = 'STEP 8: Define subsystem boundaries based on physical domain or functional role';
    guide{9} = 'STEP 9: Plan signal routing (direct connections vs Goto/From for broadcast)';
    guide{10} = 'STEP 10: Assess model complexity and assign confidence level';
end

% ===== Signal Flow Patterns: Common topologies =====
function patterns = get_signal_flow_patterns()
    patterns = {};
    % Closed-loop feedback
    patterns{1} = struct('name', 'closed_loop_feedback', ...
        'description', 'Plant output -> Controller -> Plant input (standard feedback)', ...
        'signalFlow', '{{srcSubsystem,Plant,dstSubsystem,Controller,signalName,measured}, {srcSubsystem,Controller,dstSubsystem,Plant,signalName,control_action}}');
    % Cascade control
    patterns{2} = struct('name', 'cascade_control', ...
        'description', 'Outer loop -> Inner loop -> Plant', ...
        'signalFlow', '{{srcSubsystem,Plant,dstSubsystem,InnerController,signalName,inner_measured}, {srcSubsystem,InnerController,dstSubsystem,Plant,signalName,inner_action}, {srcSubsystem,Plant,dstSubsystem,OuterController,signalName,outer_measured}, {srcSubsystem,OuterController,dstSubsystem,InnerController,signalName,setpoint}}');
    % Feedforward + feedback
    patterns{3} = struct('name', 'feedforward_feedback', ...
        'description', 'Reference -> Feedforward + Feedback Controller -> Plant', ...
        'signalFlow', '{{srcSubsystem,Reference,dstSubsystem,Feedforward,signalName,ref}, {srcSubsystem,Plant,dstSubsystem,Feedback,signalName,measured}, {srcSubsystem,Feedforward,dstSubsystem,Sum,signalName,ff_action}, {srcSubsystem,Feedback,dstSubsystem,Sum,signalName,fb_action}, {srcSubsystem,Sum,dstSubsystem,Plant,signalName,total_action}}');
end
