function result = sl_parse_error(errorMessage, varargin)
% SL_PARSE_ERROR 精确错误解析 — 15+ 种错误类型正则匹配 + 结构化诊断 + 修复建议
%   result = sl_parse_error(errorMessage)
%   result = sl_parse_error(errorMessage, 'modelName', 'MyModel')
%
%   版本策略: 纯字符串处理，无版本兼容性问题
%
%   输入:
%     errorMessage  - Simulink 错误信息字符串（必选）
%     'modelName'   - 关联模型名（可选，用于提供更精准建议）
%     'context'     - 上下文信息 struct（可选，如上次操作的参数）
%
%   输出: struct
%     .status        - 'ok'（成功解析）或 'unknown'（无匹配模式）
%     .errorAnalysis - struct:
%       .type         - 错误类型标识符
%       .confidence   - 'high' / 'medium' / 'low'
%       .description  - 错误的中文描述
%       .suggestion   - 修复建议（可直接执行的命令或步骤）
%       .relatedBlock - 关联模块路径（如能提取）
%       .severity     - 'error' / 'warning' / 'info'
%     .alternatives  - 其他可能的错误类型匹配（confidence 较低）
%     .message       - 人类可读的总结信息

    % ===== 解析参数 =====
    modelName = '';
    context = struct();
    
    idx = 1;
    while idx <= length(varargin)
        if ischar(varargin{idx}) && idx < length(varargin)
            if strcmpi(varargin{idx}, 'modelName')
                modelName = varargin{idx+1};
            elseif strcmpi(varargin{idx}, 'context')
                context = varargin{idx+1};
            end
        end
        idx = idx + 2;
    end

    result = struct('status', 'unknown', ...
        'errorAnalysis', struct('type', '', 'confidence', 'low', ...
            'description', '', 'suggestion', '', 'relatedBlock', '', 'severity', 'info'), ...
        'alternatives', {{}}, ...
        'message', '');

    if isempty(errorMessage)
        result.errorAnalysis.type = 'empty_message';
        result.errorAnalysis.description = 'Error message is empty';
        result.errorAnalysis.suggestion = 'Provide the actual Simulink error message';
        result.message = 'No error message to parse';
        return;
    end

    % ===== 定义 15 种错误模式 =====
    % 使用 struct 数组避免 cell 矩阵的行列歧义问题
    % 每个 struct: type, regex, confidence, description, suggestion, severity
    patterns = struct( ...
        'type', '', 'regex', '', 'confidence', '', 'description', '', 'suggestion', '', 'severity', '');
    
    patterns(1) = struct('type', 'port_dimension_mismatch', ...
        'regex', '(?i)dimension.*mismatch|mismatched.*dimension', ...
        'confidence', 'high', ...
        'description', 'Port dimension mismatch - signal dimensions at connection points do not match', ...
        'suggestion', 'Check signal dimensions at both ends: use sl_inspect_model to view port widths, add Mux/Demux or Conversion block as needed', ...
        'severity', 'error');
    patterns(2) = struct('type', 'target_port_occupied', ...
        'regex', '(?i)already connected|destination port.*already', ...
        'confidence', 'high', ...
        'description', 'Target port already occupied - cannot connect to an already-connected port', ...
        'suggestion', 'Delete existing line first, then reconnect: use sl_delete_safe or delete_line, then sl_add_line_safe', ...
        'severity', 'error');
    patterns(3) = struct('type', 'unresolved_variable', ...
        'regex', '(?i)undefined function or variable|unresolved.*variable', ...
        'confidence', 'high', ...
        'description', 'Undefined variable - MATLAB cannot find a referenced variable in workspace', ...
        'suggestion', 'Define the variable in base workspace: assignin(''base'', ''varName'', value) or use sl_set_param_safe to set parameter directly', ...
        'severity', 'error');
    patterns(4) = struct('type', 'algebraic_loop', ...
        'regex', '(?i)algebraic loop', ...
        'confidence', 'high', ...
        'description', 'Algebraic loop detected - direct feedthrough creates circular dependency', ...
        'suggestion', 'Add a Memory or Unit Delay block to break the loop, or set AlgebraicLoopMsg to warning in model config', ...
        'severity', 'error');
    patterns(5) = struct('type', 'invalid_block_path', ...
        'regex', '(?i)does not exist|invalid path|block.*not found', ...
        'confidence', 'high', ...
        'description', 'Invalid block path - the specified block does not exist in the model', ...
        'suggestion', 'Use sl_find_blocks or find_system to locate the correct block path', ...
        'severity', 'error');
    patterns(6) = struct('type', 'compilation_error', ...
        'regex', '(?i)error compiling|compilation error', ...
        'confidence', 'medium', ...
        'description', 'Model compilation error - Simulink cannot compile the model', ...
        'suggestion', 'Call sl_validate_model for detailed diagnosis of compilation issues', ...
        'severity', 'error');
    patterns(7) = struct('type', 'sample_time_conflict', ...
        'regex', '(?i)sample time conflict|rate transition|required.*rate transition', ...
        'confidence', 'high', ...
        'description', 'Sample time conflict - connected blocks have incompatible sample times', ...
        'suggestion', 'Add a Rate Transition block between blocks with different sample times', ...
        'severity', 'warning');
    patterns(8) = struct('type', 'data_type_mismatch', ...
        'regex', '(?i)data type mismatch|type mismatch', ...
        'confidence', 'high', ...
        'description', 'Data type mismatch - signal types at connection points do not match', ...
        'suggestion', 'Add a Data Type Conversion block between mismatched ports', ...
        'severity', 'error');
    patterns(9) = struct('type', 'bus_not_found', ...
        'regex', '(?i)bus object.*not found|undefined bus|bus.*not defined', ...
        'confidence', 'high', ...
        'description', 'Bus object not found - referenced Simulink.Bus object does not exist', ...
        'suggestion', 'Create the Bus object using sl_bus_create or define it in base workspace', ...
        'severity', 'error');
    patterns(10) = struct('type', 'block_diagram_error', ...
        'regex', '(?i)block diagram error', ...
        'confidence', 'medium', ...
        'description', 'Block diagram error - general Simulink diagram error', ...
        'suggestion', 'Call sl_validate_model for comprehensive diagnosis', ...
        'severity', 'error');
    patterns(11) = struct('type', 'mask_parameter_error', ...
        'regex', '(?i)error evaluating.*mask|mask.*parameter.*error', ...
        'confidence', 'medium', ...
        'description', 'Mask parameter evaluation error - expression in masked subsystem failed', ...
        'suggestion', 'Check mask parameter expressions: open the mask editor and verify each parameter''s evaluation', ...
        'severity', 'error');
    patterns(12) = struct('type', 'model_ref_not_found', ...
        'regex', '(?i)model.*not found|referenced model.*not found', ...
        'confidence', 'high', ...
        'description', 'Referenced model not found - Model block points to a non-existent model', ...
        'suggestion', 'Check the Model block reference path and ensure the referenced model file exists', ...
        'severity', 'error');
    patterns(13) = struct('type', 'solver_error', ...
        'regex', '(?i)invalid solver|solver error|cannot use solver', ...
        'confidence', 'high', ...
        'description', 'Solver configuration error - invalid or incompatible solver settings', ...
        'suggestion', 'Use sl_config_get to view current solver settings, then sl_config_set to correct', ...
        'severity', 'error');
    patterns(14) = struct('type', 'signal_logging_error', ...
        'regex', '(?i)unable to log|signal logging.*error', ...
        'confidence', 'medium', ...
        'description', 'Signal logging error - cannot log the specified signal', ...
        'suggestion', 'Check signal logging configuration: ensure DataLogging is enabled and signal name is unique', ...
        'severity', 'warning');
    patterns(15) = struct('type', 'codegen_error', ...
        'regex', '(?i)error generating code|build error|code generation.*error', ...
        'confidence', 'medium', ...
        'description', 'Code generation error - Simulink Coder cannot generate code', ...
        'suggestion', 'Check code generation settings with sl_config_get(''codegen''), ensure all blocks support code generation', ...
        'severity', 'error');

    % ===== 逐模式匹配 =====
    nPatterns = length(patterns);
    matches = {};
    
    for i = 1:nPatterns
        pType = patterns(i).type;
        pRegex = patterns(i).regex;
        pConfidence = patterns(i).confidence;
        pDescription = patterns(i).description;
        pSuggestion = patterns(i).suggestion;
        pSeverity = patterns(i).severity;
        
        try
            if ~isempty(regexp(errorMessage, pRegex, 'once'))
                matches{end+1} = struct('type', pType, 'confidence', pConfidence, ... %#ok<AGROW>
                    'description', pDescription, 'suggestion', pSuggestion, ...
                    'severity', pSeverity);
            end
        catch
            % 正则表达式错误，跳过
        end
    end

    % ===== 提取关联模块 =====
    relatedBlock = '';
    % 尝试从错误信息中提取模块路径（格式: 'ModelName/BlockName'）
    try
        blockMatches = regexp(errorMessage, '''(\w+/\w+)''', 'tokens');
        if ~isempty(blockMatches)
            relatedBlock = blockMatches{1}{1};
        end
    catch
    end
    % 也尝试匹配 "in 'XXX'" 格式
    if isempty(relatedBlock)
        try
            blockMatches = regexp(errorMessage, 'in\s+''([^'']+)''', 'tokens');
            if ~isempty(blockMatches)
                relatedBlock = blockMatches{1}{1};
            end
        catch
        end
    end

    % ===== 选择最佳匹配 =====
    if ~isempty(matches)
        % 按置信度排序: high > medium > low
        bestIdx = 1;
        for i = 2:length(matches)
            if strcmpi(matches{i}.confidence, 'high') && ~strcmpi(matches{bestIdx}.confidence, 'high')
                bestIdx = i;
            end
        end

        best = matches{bestIdx};
        result.status = 'ok';
        result.errorAnalysis.type = best.type;
        result.errorAnalysis.confidence = best.confidence;
        result.errorAnalysis.description = best.description;
        result.errorAnalysis.suggestion = best.suggestion;
        result.errorAnalysis.severity = best.severity;
        result.errorAnalysis.relatedBlock = relatedBlock;

        % 其他匹配作为 alternatives
        alts = {};
        for i = 1:length(matches)
            if i ~= bestIdx
                alts{end+1} = matches{i}; %#ok<AGROW>
            end
        end
        result.alternatives = alts;

        result.message = sprintf('Error type: %s (%s confidence) - %s', ...
            best.type, best.confidence, best.description);
    else
        % 无匹配 → 返回 generic 建议
        result.status = 'unknown';
        result.errorAnalysis.type = 'unknown';
        result.errorAnalysis.confidence = 'low';
        result.errorAnalysis.description = ['Unrecognized error pattern: ' errorMessage(1:min(100,length(errorMessage)))];
        result.errorAnalysis.suggestion = 'Call sl_validate_model for comprehensive diagnosis';
        result.errorAnalysis.relatedBlock = relatedBlock;
        result.errorAnalysis.severity = 'error';
        result.message = 'Could not match error to known pattern; try sl_validate_model for diagnosis';
    end
end
