function plan = sl_retry_plan(modelName, subPath, completeResult, retryState)
% SL_RETRY_PLAN v30 Auto-generate retry plan from complete failure
%   plan = sl_retry_plan(modelName, subPath, completeResult, retryState)

    plan = struct('generated', false, ...
        'failureType', '', ...
        'steps', {{}}, ...
        'remainingRetries', 0, ...
        'message', '', ...
        'autoGenerated', true);

    if nargin < 3
        plan.message = 'sl_retry_plan: completeResult required';
        return;
    end

    % ===== 1. Determine failure type =====
    failureType = 'implementation_error';

    if nargin >= 4 && isstruct(retryState) && isfield(retryState, 'repeated_failure_count')
        if retryState.repeated_failure_count >= 3
            failureType = 'design_suspect';
        end
    end

    if ~strcmp(failureType, 'design_suspect') && isstruct(completeResult)
        designCritical = {'paramAudit', 'blockPlan', 'compilation'};
        if isfield(completeResult, 'failedChecks')
            fcs = completeResult.failedChecks;
            n = numel(fcs);
            for i = 1:n
                if iscell(fcs)
                    fc = fcs{i};
                else
                    fc = fcs(i);
                end
                if isstruct(fc) && isfield(fc, 'name')
                    if any(strcmp(designCritical, fc.name))
                        failureType = 'design_suspect';
                        break;
                    end
                end
            end
        end
    end

    plan.failureType = failureType;

    % ===== 2. Generate fix steps =====
    if strcmp(failureType, 'implementation_error')
        plan.steps = generateImplRetrySteps(completeResult, subPath);
        plan.generated = ~isempty(plan.steps);
        if plan.generated
            plan.message = sprintf('Auto-generated %d implementation retry steps', length(plan.steps));
        else
            plan.message = 'No actionable retry steps could be generated from failedChecks';
        end
    else
        plan.steps = {struct('action', 'reset_subsystem', ...
            'subsystemPath', subPath, ...
            'preserveShell', true)};
        plan.generated = true;
        plan.message = 'Design issue detected. Reset subsystem preserving Inport/Outport shell, restart micro_design.';
    end

    % ===== 3. Calculate remaining retries =====
    plan.remainingRetries = calculateRemaining(retryState);
end

function steps = generateImplRetrySteps(completeResult, subPath)
    steps = {};

    if ~isfield(completeResult, 'failedChecks')
        return;
    end

    fcs = completeResult.failedChecks;
    n = numel(fcs);

    for i = 1:n
        if iscell(fcs)
            check = fcs{i};
        else
            check = fcs(i);
        end
        if ~isstruct(check) || ~isfield(check, 'name')
            continue;
        end

        switch check.name
            case 'unconnected'
                if isfield(check, 'ports')
                    ports = check.ports;
                    if iscell(ports)
                        np = min(length(ports), 5);
                        for j = 1:np
                            p = ports{j};
                            if isstruct(p) && isfield(p, 'blockPath')
                                steps{end+1} = struct('action', 'delete_block', ...
                                    'blockPath', p.blockPath, ...
                                    'reason', sprintf('unconnected port %d', j)); %#ok<AGROW>
                            end
                        end
                    end
                end
                if isempty(steps)
                    steps{end+1} = struct('action', 'inspect_unconnected', ...
                        'subsystemPath', subPath, ...
                        'reason', 'unconnected ports detected but no per-port details available'); %#ok<AGROW>
                end

            case 'layoutAudit'
                steps{end+1} = struct('action', 'auto_layout', ...
                    'target', subPath); %#ok<AGROW>

            case 'connectionScan'
                steps{end+1} = struct('action', 'inspect_connections', ...
                    'subsystemPath', subPath, ...
                    'reason', 'connection scan failed'); %#ok<AGROW>

            otherwise
                steps{end+1} = struct('action', 'inspect_check', ...
                    'checkName', check.name, ...
                    'subsystemPath', subPath, ...
                    'reason', ['check ' check.name ' failed']); %#ok<AGROW>
        end
    end

    if length(steps) > 10
        steps = steps(1:10);
    end
end

function remaining = calculateRemaining(retryState)
    remaining = 0;

    if nargin < 1 || ~isstruct(retryState)
        remaining = -1;
        return;
    end

    retryCount = 0;
    designCount = 0;
    maxImpl = 5;
    maxDesign = 5;

    if isfield(retryState, 'retry_count'), retryCount = retryState.retry_count; end
    if isfield(retryState, 'design_count'), designCount = retryState.design_count; end
    if isfield(retryState, 'max_impl_retries'), maxImpl = retryState.max_impl_retries; end
    if isfield(retryState, 'max_design_retries'), maxDesign = retryState.max_design_retries; end

    remaining = (maxImpl - retryCount) + (maxDesign - designCount);
end
